hack2019/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'hack2019.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('interview.urls')),
    url(r'^interview/', include('interview.urls')),
]

interview/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'interview'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^candidateProfile/$', views.goToCandidateProfile, name='goToCandidateProfile'),
    url(r'^test/$', views.test, name='test'),
    url(r'^candidateProfile/instructions/$', views.goToInstructionsPage, name='goToInstructionsPage'),


]

interview/models.py
from django.db import models


class InterviewQuestion(models.Model):

    interview_question_name = models.CharField(max_length=250)
    interview_question_text = models.TextField()


class InterviewAnswer(models.Model):
    question = models.ForeignKey(InterviewQuestion,on_delete=models.CASCADE)
    answer = models.TextField()

interview/views.py
from django.shortcuts import render
from django.http import HttpResponse
import pyttsx3
from gtts import gTTS
import speech_recognition as sr
import urllib3
from .models import InterviewAnswer,InterviewQuestion


def index(request):
    return render(request, 'interview/index.html')


def goToCandidateProfile(request):
    return render(request, 'interview/candidateprofileview.html')


def test(request):



    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

    f = open("assesment.txt", "a")
    questions = InterviewQuestion.objects.all()
    questionCount = 0
    cu = 0
    while (questionCount < len(questions)):
        print("Question No", questionCount, ":", questions[questionCount])
        engine = pyttsx3.init()
        engine.setProperty('rate', 140)

        r = sr.Recognizer()
        with sr.Microphone() as source:
            r.adjust_for_ambient_noise(source, duration=1)
            engine.say(questions[questionCount].interview_question_text)
            engine.runAndWait()
            engine.stop()
            print("Say something!")
            r.pause_threshold = 1
            audio = r.listen(source, phrase_time_limit=10)
        try:
            response = r.recognize_google(audio)
            answer = InterviewAnswer();
            answer.question = questions[questionCount];
            answer.answer = response;
            answer.save()

            print("I think you said :'" + response + "'")
            f.write(response + "\n")
            tts = gTTS(text="I think you said " + str(response), lang='en')
            questionCount += 1
            cu = 0

        except sr.UnknownValueError:
            print("Sphinx could not understand audio ")
            cu += 1
            if (cu == 3):
                questionCount += 1
                cu = 0

        except sr.RequestError as e:
            print("Sphinx error; {0}".format(e))




    return HttpResponse("")


def goToInstructionsPage(request):
    return render(request, 'interview/instructionpage.html')

interview/templates/interview/baseVisitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container-login100-form-btn m-t-32">
		<a href="{% url 'interview:test' %}" >
			<button class="login100-form-btn">
							interview
						</button>
		</a>


</div>
</body>
</html>

interview/templates/interview/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
	<title>ApnaApp</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'interview/css/vendor/bootstrap/css/bootstrap.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'interview/css/fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'interview/css/fonts/Linearicons-Free-v1.0.0/icon-font.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'interview/css/vendor/animate/animate.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'interview/css/vendor/css-hamburgers/hamburgers.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'interview/css/vendor/animsition/css/animsition.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'interview/css/vendor/select2/select2.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'interview/css/vendor/daterangepicker/daterangepicker.css'%}">

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'interview/css/maincss/main.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'interview/css/maincss/util.css'%}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100 ">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Account Login
				</span>
				<form action ="{% url 'interview:goToCandidateProfile' %}" method ="post" class="login100-form validate-form p-b-33 p-t-5">
					{% csrf_token %}


					<div class="wrap-input100" >
						<input class="input100" type="text" name="username" placeholder="User name">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 ">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="container-login100-form-btn m-t-32">

						<button type = "submit" class="login100-form-btn">
							Login
						</button>

					</div>

				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'interview/css/vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'interview/css/vendor/animsition/js/animsition.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'interview/css/vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{% static 'interview/css/vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'interview/css/vendor/select2/select2.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'interview/css/vendor/daterangepicker/moment.min.js'%}"></script>
	<script src="{% static 'interview/css/vendor/daterangepicker/daterangepicker.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'interview/css/vendor/countdowntime/countdowntime.js'%}"></script>
<!--===============================================================================================-->
	    <script src="{% static 'interview/js/main.js' %}"></script>

</body>
</html>

interview/templates/interview/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>
    bolo beta
</h1>
</body>
</html>